import { ApiService } from './../../services/api.service';
import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'app-novelas',
    templateUrl: './novelas.component.html',
    styleUrls: ['./novelas.component.sass']
})

export class NovelasComponent implements OnInit {

    novelArray: any[] = [
        { titulo: 'testing 1' },
        { titulo: 'testing 2' },
        { titulo: 'testing 3' },
        // {titulo: 'testing 5'},
        // {titulo: 'testing 6'},
        // {titulo: 'testing 7'},
        // {titulo: 'testing 8'},
        // {titulo: 'testing 9'},
        // {titulo: 'testing 9'},
        // {titulo: 'testing 1'},
        // {titulo: 'testing 2'},
        // {titulo: 'testing 4'},
        // {titulo: 'testing 5'},
        // {titulo: 'testing 6'},
        // {titulo: 'testing 7'},
        // {titulo: 'testing 8'},
        // {titulo: 'testing 9'},
        // {titulo: 'testing 9'},
        // {titulo: 'testing 1'},
        // {titulo: 'testing 2'},
        // {titulo: 'testing 4'},
        // {titulo: 'testing 5'},
        // {titulo: 'testing 6'},
        // {titulo: 'testing 7'},
        // {titulo: 'testing 8'},
        // {titulo: 'testing 9'},
        // {titulo: 'testing 9'},
        // {titulo: 'testing 1'},
        // {titulo: 'testing 2'},
        // {titulo: 'testing 4'},
        // {titulo: 'testing 5'},
        // {titulo: 'testing 6'},
        // {titulo: 'testing 7'},
        // {titulo: 'testing 8'},
        // {titulo: 'testing 9'},
        // {titulo: 'testing 9'},
        // {titulo: 'testing 1'},
        // {titulo: 'testing 2'},
        // {titulo: 'testing 4'},
        // {titulo: 'testing 5'},
        // {titulo: 'testing 6'},
        // {titulo: 'testing 7'},
        // {titulo: 'testing 8'},
        // {titulo: 'testing 9'},
        // {titulo: 'testing 9'},
        // {titulo: 'testing 1'},
        // {titulo: 'testing 2'},
        // {titulo: 'testing 4'},
        // {titulo: 'testing 5'},
        // {titulo: 'testing 6'},
        // {titulo: 'testing 7'},
        // {titulo: 'testing 8'},
        // {titulo: 'testing 9'},
        // {titulo: 'testing 9'},
        // {titulo: 'testing 1'},
        // {titulo: 'testing 2'},
        // {titulo: 'testing 4'},
        // {titulo: 'testing 5'},
        // {titulo: 'testing 6'},
        // {titulo: 'testing 7'},
        // {titulo: 'testing 8'},
        // {titulo: 'testing 9'},
        // {titulo: 'testing 9'},
        // {titulo: 'testing 1'},
        // {titulo: 'testing 2'},
        // {titulo: 'testing 4'},
        // {titulo: 'testing 5'},
        // {titulo: 'testing 6'},
        // {titulo: 'testing 7'},
        // {titulo: 'testing 8'},
        // {titulo: 'testing 9'},
        // {titulo: 'testing 9'},
        // {titulo: 'testing 1'},
        // {titulo: 'testing 2'},
        // {titulo: 'testing 4'},
        // {titulo: 'testing 5'},
        // {titulo: 'testing 6'},
        // {titulo: 'testing 7'},
        // {titulo: 'testing 8'},
        // {titulo: 'testing 9'},
        // {titulo: 'testing 9'},
        // {titulo: 'testing 1'},
        // {titulo: 'testing 2'},
        // {titulo: 'testing 4'},
        // {titulo: 'testing 5'},
        // {titulo: 'testing 6'},
        // {titulo: 'testing 7'},
        // {titulo: 'testing 8'},
        // {titulo: 'testing 9'},
        // {titulo: 'testing 9'},
        // {titulo: 'testing 1'},
        // {titulo: 'testing 2'},
        // {titulo: 'testing 4'},
        // {titulo: 'testing 5'},
        // {titulo: 'testing 6'},
        // {titulo: 'testing 7'},
        // {titulo: 'testing 8'},
        // {titulo: 'testing 9'},
        // {titulo: 'testing 9'},
        // {titulo: 'testing 1'},
        // {titulo: 'testing 2'},
        // {titulo: 'testing 4'},
        // {titulo: 'testing 5'},
        // {titulo: 'testing 6'},
        // {titulo: 'testing 7'},
        // {titulo: 'testing 8'},
        // {titulo: 'testing 9'},
        // {titulo: 'testing 9'},


    ]
    constructor( apiService: ApiService) {
        
    }
     

    ngOnInit() {
    }

}
